name: Workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest 

    steps:
      - name: Run Welcome Message
        run: echo "First GitHub Actions Trial"

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: List Files
        run: ls -la
   
