name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # --- Diagnostic steps (keep these for now) ---
      - name: Debug - List contents of repository root
        run: ls -la .

      - name: Debug - List contents of ./my-app directory
        run: ls -la ./my-app

      - name: Debug - Attempt to read ./my-app/Dockerfile content
        run: cat ./my-app/Dockerfile || echo "Could not read Dockerfile content"
      # --- End of diagnostic steps ---

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alaametawe/my-app

      - name: Debug metadata action output
        run: |
          echo "Generated tags by metadata-action: ${{ steps.meta.outputs.tags }}"
          echo "Generated labels by metadata-action: ${{ steps.meta.outputs.labels }}"

      # --- NEW: Manual Build and push Docker image (DEBUG) ---
      - name: Manual Build and push Docker image (DEBUG)
        env:
          BUILD_TAGS: ${{ steps.meta.outputs.tags }}
          BUILD_LABELS: ${{ steps.meta.outputs.labels }}
        run: |
          echo "--- Starting manual buildx command ---"
          echo "Current working directory: $(pwd)"
          echo "Contents of my-app directory immediately before buildx:"
          ls -la ./my-app

      # NOTE: Remove the 'Generate artifact attestation' for now,
      # as it relies on 'steps.push.outputs.digest' which won't be set by a manual 'run' step.
      # We can add it back later if the build works.

