name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # --- Diagnostic steps (keep these for now) ---
      - name: Debug - List contents of repository root
        run: ls -la .

      - name: Debug - List contents of ./my-app directory
        run: ls -la ./my-app

      - name: Debug - Attempt to read ./my-app/Dockerfile content
        run: cat ./my-app/Dockerfile || echo "Could not read Dockerfile content"
      # --- End of diagnostic steps ---

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alaametawe/my-app

      # --- NEW DIAGNOSTIC STEP ---
      - name: Debug metadata action output
        run: |
          echo "Generated tags by metadata-action: ${{ steps.meta.outputs.tags }}"
          echo "Generated labels by metadata-action: ${{ steps.meta.outputs.labels }}"
      # --- END NEW DIAGNOSTIC STEP ---

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./my-app
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/alaametawe/my-app
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true


