name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # --- Diagnostic steps (you can remove these after the build works) ---
      - name: Debug - List contents of repository root
        run: ls -la .

      - name: Debug - List contents of ./my-app directory
        run: ls -la ./my-app

      - name: Debug - Attempt to read ./my-app/Dockerfile content
        run: cat ./my-app/Dockerfile || echo "Could not read Dockerfile content"
      # --- End of diagnostic steps ---

      - name: Log in to Docker Hub
        # CORRECTED: Use the stable v3 tag for docker/login-action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

